name: Custom ENV Variables

on: ['push']

env:
    Last_Day: Friday

jobs:
    Accessing-All-Level-ENV:
        runs-on: windows-latest
        env:
            Current_Day: Wednesday
        steps:
            - name: Printing All ENV
              run: echo "$Last_Day Days Worked and The Remaining Days are $Current_Day. $Greet"
              env:
                Greet: Enjoy
