name: Custom ENV Variables

on: ['push']

env:
    Last_Day: Friday

jobs:
    Accessing-All-Level-ENV:
        runs-on: windows-latest
        env:
            Current_Day: Wednesday
        steps:
            - name: Printing All ENV
              run: |
                echo Last_Day: %Last_Day%
                echo Current_Day: %Current_Day%
                echo Greet: %Greet%
              env:
                Greet: Enjoy Karo.
