name: Custom ENV Variables

on: ['push']

env:
    day: Friday

jobs:
    Accessing-All-Level-ENV:
        runs-on: windows-latest
        env:
            current: Wednesday
        steps:
            - name: Printing All ENV
              run: |
                echo Last_Day: %day%
                echo Current_Day: %current%
                echo Greet: %greet%
              env:
                greet: Enjoy Karo.
