name: Custom ENV Variables

on: ['push']

jobs:
    Accessing-All-Level-ENV:
        runs-on: ubuntu-latest
        env:
            current: "Friday"
        steps:
            - name: Printing All ENV
              run: |
                echo Current_Day: $current
                echo Greet: $greet
              env:
                greet: Enjoy Karo.
