name: Custom ENV Variables

on: ['push']

env:
    NOWDR: "2"

jobs:
    Accessing-All-Level-ENV:
        runs-on: windows-latest
        env:
            NOWD: "3"
        steps:
            - name: Printing All ENV
              run: echo You Worked for $NOWD and The Remaining Days are $NOWDR. $greet
              env:
                greet: "Then, Have a Weekend"
