name: Custom ENV Variables

on: ['push']

env:
    NOWDR: 2

jobs:
    Accessing-All-Level-ENV:
        runs-on: windows-latest
        env:
            NOWD: 3
        steps:
            - name: Printing All ENV
              run: echo "$NOWD Days Worked and The Remaining Days are $NOWDR. $greet"
              env:
                greet: Enjoy
