name: Custom ENV Variables

on: ['push']

env:
    last_day: Friday

jobs:
    Accessing-All-Level-ENV:
        runs-on: ubuntu-latest
        env:
            current: Wednesday
        steps:
            - name: Printing All ENV
              run: |
                echo Last_Day: ${{last_day}}
                echo Current_Day: ${{current}}
                echo Greet: ${{greet}}
              env:
                greet: Enjoy Karo.
