name: Expression-Function-Trigger

on:
    push:
        branches:
            - main
            - feature

jobs:
    Predefined-Expressions:
        runs-on: ubuntu-latest

        steps:
            - name: StartsWith()
              if:   startsWith('Hello', 'el')
              run:  echo "It contains the Mention Letters"