name: Expression-Function-Trigger

on:
    push:
        branches:
            - main
            - feature

jobs:
    Predefined-Expressions:
        runs-on: ubuntu-latest
        steps:
            - name: Checking that the String contains the Given Letters
              if: startsWith('Hello', 'Hel')
              run: echo "It Starts with the Mentioned Letters"