name: GitHub-Contexts

on: ['push']

jobs:
    Contexts:
        runs-on: ubuntu-latest
        steps:
            - name: Using github.action
              run: echo "The Github_Action is:$Action"
              env:
                Action: ${{github.action}}