name: GitHub-Contexts

on: ['push']

jobs:
    Contexts:
        runs-on: ubuntu-latest
        steps:
            - name: Using github.action to check Internal Variables
              run: |
                echo The Github_Action is:$Action
                echo The Github_Actor is:$Repository
                echo The Secret Token used here:$Secrets
                echo The Secret Token used here:${{github.event_name}}
              env:
                Action: ${{github.action}}
                Repository: ${{github.actor}}
                Secrets: ${{secrets.GITHUB_TOKEN}}