name: Java Installation

on: push

jobs:
  Java-JDK-Setup:
    name: Setting Java JDK in Ubuntu Machine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Action
        uses: actions/checkout@v3

      - name: JDK-SETUP
        uses: oracle-actions/setup-java@v1.3.4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
