name: Workflow-Commands

on: ['push','pull_request']

jobs:
    Group-Message:
        runs-on: ubuntu-latest
        steps:
            - name: Group-Log
              run: |
                   echo "::group::Group Message"
                   echo "Hey, sanjay"
                   echo "May I know the Status of Your Task ?"
                   echo "We can have a little Change here!"
                   echo "::endgroup::"
            - name: Store Value in a Variable
              run: echo "VAR=Jayasundar" >> $GITHUB_ENV
            - name: Retriving the Stored value
              run: echo $VAR